// CapyWork (카피 출근부) — menu bar capybaras for your Claude Code sessions.
// Reads ~/.capywork/log/<today>.jsonl written by hook.sh.
import SwiftUI
import AppKit
import Carbon

func logURL(_ day: Date) -> URL {
    // Local-time day, matching `date +%F` in hook.sh.
    let name = day.formatted(Date.ISO8601FormatStyle(timeZone: .current).year().month().day())
    return FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent(".capywork/log/\(name).jsonl")
}

func openSession(_ e: Employee) {
    guard let id = e.deskId, let url = URL(string: "claude://code/continue?session=\(id)") else { return NSSound.beep() }
    NSWorkspace.shared.open(url)
}

/// Global ⌃⌥⌘C via Carbon (no Accessibility permission needed).
nonisolated(unsafe) var hotKeyAction: (() -> Void)?
func registerHotKey(_ action: @escaping () -> Void) {
    hotKeyAction = action
    var spec = EventTypeSpec(eventClass: OSType(kEventClassKeyboard), eventKind: UInt32(kEventHotKeyPressed))
    InstallEventHandler(GetApplicationEventTarget(), { _, _, _ in hotKeyAction?(); return noErr }, 1, &spec, nil, nil)
    var ref: EventHotKeyRef?
    RegisterEventHotKey(UInt32(kVK_ANSI_C), UInt32(controlKey | optionKey | cmdKey),
                        EventHotKeyID(signature: OSType(0x434F_4646), id: 1), GetApplicationEventTarget(), 0, &ref)
}

enum WorkState: Int, Comparable {
    case idle, working, waiting  // higher = shown in menu bar
    static func < (a: Self, b: Self) -> Bool { a.rawValue < b.rawValue }
    var label: String { ["대기", "근무 중", "결재 대기"][rawValue] }
    var nsColor: NSColor {
        [NSColor.secondaryLabelColor,
         NSColor(srgbRed: 0.85, green: 0.47, blue: 0.34, alpha: 1),  // Claude orange
         NSColor.systemRed][rawValue]
    }
    var color: Color { Color(nsColor: nsColor) }
}

struct Employee: Identifiable {
    let id: String
    let project: String
    var state = WorkState.idle
    var task = ""
    var since: Date
    var last: Date
    var title = ""      // desktop app session title, if any
    var deskId: String? // desktop app session id → clickable
    var done: Date?     // when the last turn finished
    var fails = 0       // consecutive tool failures
    var flailing: Bool { state == .working && fails >= 2 }
    var unread = false  // finished after you last looked
    var name: String { title.isEmpty ? project : title }
    var needsYou: Bool { state == .waiting || unread }
    var rank: Int { state == .waiting ? 3 : unread ? 2 : state == .working ? 1 : 0 }
    var color: Color { flailing ? .red : unread && state == .idle ? .blue : state.color }
    var label: String { flailing ? "에러 반복" : unread && state == .idle ? "새 답변" : state.label }
}

/// Menu bar capybaras, 26×15 pixel art (generated by capy.py), one per session:
/// swims while working (🌙 after 7pm, flails on repeated tool errors), munches grass on an
/// unread answer, rolls a yuzu when it needs approval (blinking once it's been 5+ min),
/// flings the yuzu when a session clocks out, and naps when nothing's going on.
enum Pose: Hashable {
    case sleep
    case swim(Int, night: Bool)
    case flail(Int)
    case chew(Int)
    case roll(Int, urgent: Bool)
    case toss(Int)
}

let swimFrames: [[String]] = [
    [
        "..........................",
        "..........................",
        "................l.........",
        "...............l..........",
        "..............ooo.........",
        ".............ooooo........",
        "...........dd.ooo.........",
        "...........dddddddd.......",
        "..........d########dd.....",
        ".....ddddd#####x#####x....",
        "...dd################d....",
        "..d##################d....",
        "ww##ww##ww##ww##ww##ww..ww",
        "..ww..ww..ww..ww..ww..ww..",
        "..........................",
    ],
    [
        "..........................",
        "..........................",
        "..........................",
        "................l.........",
        "...............l..........",
        "..............ooo.........",
        "...........ddooooo........",
        "...........dddooodd.......",
        "..........d########dd.....",
        ".....ddddd#####x#####x....",
        "...dd################d....",
        "..d##################d....",
        ".dww##ww##ww##ww##ww#dww..",
        "ww..ww..ww..ww..ww..ww..ww",
        "..........................",
    ],
    [
        "..........................",
        "..........................",
        "................l.........",
        "...............l..........",
        "..............ooo.........",
        ".............ooooo........",
        "...........dd.ooo.........",
        "...........dddddddd.......",
        "..........d########dd.....",
        ".....ddddd#####x#####x....",
        "...dd################d....",
        "..d##################d....",
        "ww##ww##ww##ww##ww##ww..ww",
        "..ww..ww..ww..ww..ww..ww..",
        "..........................",
    ],
]
let flailFrames: [[String]] = [
    [
        "..........................",
        "..........................",
        "..............l...........",
        ".............l............",
        "............ooo...........",
        "...........ooooo..........",
        "............ooo...........",
        "...........dd............w",
        "....w......dddddddd.......",
        ".......dddd########dd..w..",
        "..wdddd########x#####x....",
        "..d##################d....",
        "wwd#ww##ww##ww##ww##ww..ww",
        "..ww..ww..ww..ww..ww..ww..",
        "..........................",
    ],
    [
        "..........................",
        "..........................",
        "..................l.......",
        ".................l........",
        "................ooo.......",
        "...............ooooo......",
        "...........dd...ooo.......",
        "...........dddddddd...w...",
        "...w......d########dd.....",
        "..........d####x#####x..w.",
        ".....wdddd###########d....",
        "...dd################d....",
        "w.dww##ww##ww##ww##wwd.ww.",
        ".ww..ww..ww..ww..ww..ww..w",
        "..........................",
    ],
]
let chewFrames: [[String]] = [
    [
        "...............l..........",
        "..............ooo.........",
        ".............ooooo........",
        "...........dd.ooo.........",
        "...........dddddddd.......",
        "..........d########dd.....",
        ".....ddddd#####x#####x...g",
        "..ddd################d..g.",
        ".d###################d.g..",
        ".d###################dg...",
        ".d############ddddddd..gg.",
        ".d###########d...........g",
        "..d#########d.............",
        "...d#ddddd#d..............",
        "...dd.....dd..............",
    ],
    [
        "...............l..........",
        "..............ooo.........",
        ".............ooooo........",
        "...........dd.ooo.........",
        "...........dddddddd.......",
        "..........d########dd.....",
        ".....ddddd#####x#####x....",
        "..ddd################d.g..",
        ".d###################dg...",
        ".d##################dg....",
        ".d############dddddd..g...",
        ".d###########d.........g..",
        "..d#########d.............",
        "...d#ddddd#d..............",
        "...dd.....dd..............",
    ],
]
let rollFrames: [[String]] = [
    [
        "..........................",
        "..........................",
        "..........................",
        "...........dd.............",
        "...........dddddddd.......",
        "..........d########dd.....",
        ".....ddddd#####x#####x....",
        "..ddd################d....",
        ".d###################d....",
        ".d###################d.l..",
        ".d############ddddddd.hOO.",
        ".d###########d.......OOOOO",
        "..d#########d.........OOO.",
        "...d#ddddd#d...........O..",
        "...dd.....dd..............",
    ],
    [
        "..........................",
        "..........................",
        "..........................",
        "...........dd.............",
        "...........dddddddd.......",
        "..........d########dd.....",
        ".....ddddd#####x#####x....",
        "..ddd################d....",
        ".d###################d....",
        ".d###################d.O..",
        ".d############ddddddd.hOO.",
        ".d###########d.......OOOOl",
        "..d#########d.........OOO.",
        "...d#ddddd#d...........O..",
        "...dd.....dd..............",
    ],
    [
        "..........................",
        "..........................",
        "..........................",
        "...........dd.............",
        "...........dddddddd.......",
        "..........d########dd.....",
        ".....ddddd#####x#####x....",
        "..ddd################d....",
        ".d###################d....",
        ".d###################d.O..",
        ".d############ddddddd.hOO.",
        ".d###########d.......OOOOO",
        "..d#########d.........OOO.",
        "...d#ddddd#d...........l..",
        "...dd.....dd..............",
    ],
]
let tossFrames: [[String]] = [
    [
        "...............l..........",
        "..............ooo.........",
        ".............ooooo........",
        "...........dd.ooo.........",
        "...........dddddddd.......",
        "..........d########dd.....",
        ".....ddddd#####x#####x....",
        "..ddd################d....",
        ".d###################d....",
        ".d###################d....",
        ".d############ddddddd.....",
        ".d###########d............",
        "..d#########d.............",
        "...d#ddddd#d..............",
        "...dd.....dd..............",
    ],
    [
        "................ooo.......",
        "...............ooooo......",
        "...........dd...ooo.......",
        "...........dddddddd.......",
        "..........d########dd.....",
        ".....ddddd#####x#####x....",
        "..ddd################d....",
        ".d###################d....",
        ".d###################d....",
        ".d############ddddddd.....",
        ".d###########d............",
        "..d#########d.............",
        "...d#ddddd#d..............",
        "...dd.....dd..............",
        "..........................",
    ],
    [
        ".................s.ooo....",
        "..................ooooo...",
        "...........dd......ooo....",
        "...........dddddddd....s..",
        "..........d#######sdd.....",
        ".....ddddd#####x#####x....",
        "..ddd################d....",
        ".d###################d....",
        ".d###################d....",
        ".d############ddddddd.....",
        ".d###########d............",
        "..d#########d.............",
        "...d#ddddd#d..............",
        "...dd.....dd..............",
        "..........................",
    ],
    [
        "........................l.",
        ".......................l..",
        "....................s.ooo.",
        "...........dd........ooooo",
        "...........dddddddd...ooo.",
        "..........d########dd.....",
        ".....ddddd#####x#####s....",
        "..ddd################d....",
        ".d###################d....",
        ".d###################d....",
        ".d############ddddddd.....",
        ".d###########d............",
        "..d#########d.............",
        "...d#ddddd#d..............",
        "...dd.....dd..............",
    ],
]
let sleepRows: [String] = [
    "..........................",
    "....................zzzz..",
    "......................z...",
    "................l....z....",
    "...............l....zzzz..",
    "..............ooo.........",
    ".............ooooo........",
    "...........dd.ooo.........",
    "...........dddddddd.......",
    "..........d########dd.....",
    ".......ddd#####xx####x....",
    "...dddd##############d....",
    ".dd##################d....",
    ".d###################d....",
    ".dddddddddddddddddddd.....",
]
let moonPixels: [(Int, Int)] = [(2, 0), (3, 0), (1, 1), (1, 2), (2, 3), (3, 3)]

func poseRows(_ p: Pose) -> [String] {
    switch p {
    case .swim(let i, _): return swimFrames[i % swimFrames.count]
    case .flail(let i): return flailFrames[i % flailFrames.count]
    case .chew(let i): return chewFrames[i % chewFrames.count]
    case .roll(let i, _): return rollFrames[i % rollFrames.count]
    case .toss(let i): return tossFrames[min(i, tossFrames.count - 1)]
    case .sleep: return sleepRows
    }
}

func pixelColor(_ c: Character) -> NSColor {
    switch c {
    case "d": return NSColor(srgbRed: 0.45, green: 0.29, blue: 0.17, alpha: 1)  // outline
    case "x": return NSColor(srgbRed: 0.2, green: 0.12, blue: 0.08, alpha: 1)   // eye, nose
    case "p": return NSColor(srgbRed: 0.95, green: 0.55, blue: 0.55, alpha: 1)  // blush
    case "o": return .systemOrange                                              // yuzu
    case "O": return NSColor(srgbRed: 1, green: 0.42, blue: 0, alpha: 1)        // vivid yuzu (needs approval)
    case "h": return NSColor(srgbRed: 1, green: 0.9, blue: 0.6, alpha: 1)       // yuzu shine
    case "l", "g": return .systemGreen                                          // leaf, grass
    case "w": return .systemTeal                                                // water
    case "s", "m": return NSColor(srgbRed: 1, green: 0.85, blue: 0.3, alpha: 1)  // sparkle, moon
    case "z": return .labelColor
    default: return NSColor(srgbRed: 0.76, green: 0.55, blue: 0.36, alpha: 1)   // fur
    }
}

let px: CGFloat = 1.5   // 3 device px on Retina → crisp
let catW = 26 * px, catH = 15 * px  // 39×22.5pt

func menuIcon(_ poses: [Pose], more: Int) -> NSImage {
    let gap: CGFloat = 3
    let moreText = more > 0 ? "+\(more)" as NSString : nil
    let attrs: [NSAttributedString.Key: Any] = [.font: NSFont.systemFont(ofSize: 11, weight: .semibold), .foregroundColor: NSColor.labelColor]
    let moreW = moreText.map { $0.size(withAttributes: attrs).width + gap } ?? 0
    let w = CGFloat(poses.count) * catW + CGFloat(poses.count - 1) * gap + moreW
    let img = NSImage(size: NSSize(width: w, height: catH), flipped: true) { _ in
        for (i, pose) in poses.enumerated() {
            let ox = CGFloat(i) * (catW + gap)
            var blink = false
            if case .roll(let f, true) = pose { blink = f % 2 == 1 }  // neglected approval: yuzu flashes red
            for (y, row) in poseRows(pose).enumerated() {
                for (x, c) in row.enumerated() where c != "." {
                    (blink && c == "O" ? NSColor.systemRed : pixelColor(c)).setFill()
                    NSRect(x: ox + CGFloat(x) * px, y: CGFloat(y) * px, width: px, height: px).fill()
                }
            }
            if case .swim(_, true) = pose {
                pixelColor("m").setFill()
                for (x, y) in moonPixels { NSRect(x: ox + CGFloat(x) * px, y: CGFloat(y) * px, width: px, height: px).fill() }
            }
        }
        moreText?.draw(at: NSPoint(x: w - moreW + gap, y: (catH - 14) / 2), withAttributes: attrs)
        return true
    }
    img.isTemplate = false
    return img
}

final class Ticker: ObservableObject {
    @Published var frame = 0
    private var timer: Timer?
    init() { timer = Timer.scheduledTimer(withTimeInterval: 0.15, repeats: true) { [weak self] _ in self?.frame += 1 } }
}

struct Report {
    var staff: [Employee] = []
    var clockIn: Date?
    var orders = 0
    var worked: TimeInterval = 0
    var ended: [(id: String, at: Date)] = []
}

func parse(_ text: String, now: Date) -> Report {
    var r = Report()
    var staff: [String: Employee] = [:]
    var workStart: [String: Date] = [:]
    func punchOut(_ sid: String, _ t: Date) {
        if let w = workStart.removeValue(forKey: sid) { r.worked += t.timeIntervalSince(w) }
    }
    for line in text.split(separator: "\n") {
        guard let o = try? JSONSerialization.jsonObject(with: Data(line.utf8)) as? [String: Any],
              let ts = o["ts"] as? Double, let e = o["e"] as? String, let sid = o["sid"] as? String
        else { continue }
        let t = Date(timeIntervalSince1970: ts)
        r.clockIn = r.clockIn ?? t
        let cwd = (o["cwd"] as? String) ?? "?"
        let project = cwd.contains("/scratch-workspaces/") ? "임시 작업"
            : cwd.split(separator: "/").last.map(String.init) ?? "?"
        var s = staff[sid] ?? Employee(id: sid, project: project, since: t, last: t)
        let old = s.state
        switch e {
        case "UserPromptSubmit":
            r.orders += 1
            s.state = .working
            s.done = nil
            s.fails = 0
            // System-injected turns (<task-notification> etc.) aren't real orders.
            let p = (o["prompt"] as? String ?? "").replacingOccurrences(of: "\n", with: " ")
            if !p.hasPrefix("<") { s.task = p }
            workStart[sid] = workStart[sid] ?? t
        case "PostToolUse", "PostToolUseFailure":
            s.state = .working
            s.fails = e == "PostToolUse" ? 0 : s.fails + 1
            workStart[sid] = workStart[sid] ?? t
        case "Notification":
            // Only permission prompts count; the 60s "waiting for input" ping is just idle.
            if (o["msg"] as? String ?? "").contains("permission") { s.state = .waiting }
        case "Stop":
            s.state = .idle
            s.done = t
            punchOut(sid, t)
        case "SessionEnd":
            punchOut(sid, t)
            if staff[sid] != nil { r.ended.append((sid, t)) }
            staff[sid] = nil
            continue
        default: break  // SessionStart: just clock in
        }
        if s.state != old { s.since = t }
        s.last = t
        staff[sid] = s
    }
    for (sid, w) in workStart where staff[sid] != nil { r.worked += now.timeIntervalSince(w) }
    // ponytail: sessions killed without SessionEnd linger; drop after 3h of silence.
    r.staff = staff.values.filter { now.timeIntervalSince($0.last) < 3 * 3600 }
        .sorted { ($0.rank, $0.last) > ($1.rank, $1.last) }  // needs-you first, then most recent
    return r
}

struct Desk {
    let cli, id, title: String
    let url: URL
    let mtime: Date
    let focused: Date  // last time you opened this session in the Claude app
}

func mtime(_ u: URL) -> Date? {
    (try? FileManager.default.attributesOfItem(atPath: u.path))?[.modificationDate] as? Date
}

func readDesk(_ u: URL) -> Desk? {
    guard let data = try? Data(contentsOf: u),
          let o = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
          let cli = o["cliSessionId"] as? String, let id = o["sessionId"] as? String, let m = mtime(u)
    else { return nil }
    let focusedMs = (o["lastFocusedAt"] as? Double) ?? 0
    return Desk(cli: cli, id: id, title: o["title"] as? String ?? "", url: u, mtime: m,
                focused: Date(timeIntervalSince1970: focusedMs / 1000))
}

/// Plan usage window (5-hour or weekly).
struct Limit { var pct: Double; var resets: Date? }
struct Limits { var five: Limit?; var week: Limit? }

/// No login needed: Claude Code's statusLine hands us `rate_limits` (statusline.sh saves it),
/// and the Claude app logs 15-min usage samples (no reset times). Newest percentage wins.
func readLimits(now: Date) -> Limits {
    var out = Limits()
    var snapAt = Date.distantPast
    let home = FileManager.default.homeDirectoryForCurrentUser
    if let d = try? Data(contentsOf: home.appendingPathComponent(".capywork/limits.json")),
       let o = try? JSONSerialization.jsonObject(with: d) as? [String: Any],
       let ts = o["ts"] as? Double, let rl = o["rate_limits"] as? [String: Any] {
        snapAt = Date(timeIntervalSince1970: ts)
        for (key, kp) in [("five_hour", \Limits.five), ("seven_day", \Limits.week)] {
            guard let w = rl[key] as? [String: Any], let p = w["used_percentage"] as? Double else { continue }
            let r = (w["resets_at"] as? Double).map { Date(timeIntervalSince1970: $0) }
            let expired = r.map { $0 <= now } ?? false
            out[keyPath: kp] = Limit(pct: expired ? 0 : p, resets: expired ? nil : r)  // window rolled over
        }
    }
    if let d = try? Data(contentsOf: home.appendingPathComponent("Library/Application Support/Claude/plan-usage-history.json")),
       let o = try? JSONSerialization.jsonObject(with: d) as? [String: Any],
       let last = (o["samples"] as? [[String: Any]])?.last,
       let t = last["t"] as? Double, let u = last["u"] as? [String: Double],
       Date(timeIntervalSince1970: t / 1000) > snapAt {
        if let fh = u["fh"] { out.five = Limit(pct: fh, resets: out.five?.resets) }
        if let sd = u["sd"] { out.week = Limit(pct: sd, resets: out.week?.resets) }
    }
    return out
}

final class Office: ObservableObject {
    @Published var report = Report()
    @Published var limits = Limits()
    @Published var history: [Date: TimeInterval] = [:]  // day start → worked
    private var historyDay = Date.distantPast
    private var backfill: [Date: TimeInterval] = [:]  // pre-hook days, from backfill.py
    private var alerted = Set<String>()
    private var timer: Timer?
    private var desk: [String: Desk] = [:]  // CLI session id → desktop session
    private var seen: [String: Date] = [:]  // finishes you watched happen / opened from here
    private var lastDone: [String: Date] = [:]
    private var nagged = Set<String>()                 // approvals already re-alerted at 5 min
    private var celebrated = Set<String>()
    @Published var celebrating: [Date] = []            // when each clock-out fling started
    private var lastScan = Date.distantPast

    init() {
        reload()
        registerHotKey { [weak self] in
            // Staff is sorted needs-you first, so the first openable one is the right target.
            guard let e = self?.report.staff.first(where: { $0.deskId != nil }) else { return NSSound.beep() }
            self?.open(e)
        }
        // ponytail: 2s polling re-reads the whole day file; switch to a file watcher if it gets big.
        timer = Timer.scheduledTimer(withTimeInterval: 2, repeats: true) { [weak self] _ in self?.reload() }
    }

    func reload() {
        let today = Calendar.current.startOfDay(for: Date())
        if historyDay != today { loadHistory(today) }
        var r = parse((try? String(contentsOf: logURL(today), encoding: .utf8)) ?? "", now: Date())
        history[today] = max(r.worked, backfill[today] ?? 0)
        if r.staff.contains(where: { desk[$0.id] == nil }), Date().timeIntervalSince(lastScan) > 30 {
            scanDesktopSessions()
        }
        let watching = NSWorkspace.shared.frontmostApplication?.bundleIdentifier == "com.anthropic.claudefordesktop"
            ? desk.max { $0.value.focused < $1.value.focused }?.key : nil
        for i in r.staff.indices {
            let sid = r.staff[i].id
            guard var d = desk[sid] else { continue }  // ponytail: terminal-only sessions never count as unread
            if let m = mtime(d.url), m != d.mtime, let fresh = readDesk(d.url) { d = fresh; desk[sid] = d }
            r.staff[i].deskId = d.id
            r.staff[i].title = d.title
            guard let done = r.staff[i].done else { continue }
            // A turn that finished while you were looking at it is already read.
            if done != lastDone[sid] { lastDone[sid] = done; if sid == watching { seen[sid] = done } }
            r.staff[i].unread = r.staff[i].state == .idle && done > max(d.focused, seen[sid] ?? .distantPast)
        }
        r.staff.sort { ($0.rank, $0.last) > ($1.rank, $1.last) }
        report = r
        limits = readLimits(now: Date())
        let waiting = Set(report.staff.filter { $0.state == .waiting }.map(\.id))
        for e in report.staff where waiting.contains(e.id) && !alerted.contains(e.id) {
            notify("결재 대기 · \(e.name)", "Claude가 권한 승인을 기다리고 있어요")
        }
        alerted = waiting
        for e in report.staff where e.state == .waiting && !nagged.contains(e.id) && Date().timeIntervalSince(e.since) > 300 {
            notify("결재 5분째 대기 · \(e.name)", "귤이 빨개지고 있어요 🍊")
            nagged.insert(e.id)
        }
        nagged.formIntersection(waiting)
        // Clock-out fling: only for sessions that ended in the last few seconds.
        for end in r.ended where !celebrated.contains(end.id) {
            celebrated.insert(end.id)
            if Date().timeIntervalSince(end.at) < 10 { celebrating.append(Date()) }
        }
        celebrating.removeAll { Date().timeIntervalSince($0) > 2.4 }
    }

    func open(_ e: Employee) {
        seen[e.id] = Date()
        openSession(e)
        reload()
    }

    /// Past days never change, so read them once (and again after midnight).
    private func loadHistory(_ today: Date) {
        historyDay = today
        let cal = Calendar.current
        let url = FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent(".capywork/backfill.json")
        if let d = try? Data(contentsOf: url), let o = try? JSONSerialization.jsonObject(with: d) as? [String: Double] {
            let f = Date.ISO8601FormatStyle(timeZone: .current).year().month().day()
            for (k, v) in o { if let day = try? f.parse(k) { backfill[cal.startOfDay(for: day)] = v } }
        }
        history = backfill
        for i in 1..<7 {
            let d = cal.date(byAdding: .day, value: -i, to: today)!
            guard let t = try? String(contentsOf: logURL(d), encoding: .utf8) else { continue }
            history[d] = max(history[d] ?? 0, parse(t, now: cal.date(byAdding: .day, value: 1, to: d)!).worked)
        }
    }

    /// The Claude desktop app keeps one JSON per Code session, linking its id to the CLI session id.
    private func scanDesktopSessions() {
        lastScan = Date()
        let root = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Library/Application Support/Claude/claude-code-sessions")
        guard let files = FileManager.default.enumerator(at: root, includingPropertiesForKeys: nil) else { return }
        for case let u as URL in files where u.lastPathComponent.hasPrefix("local_") && u.pathExtension == "json" {
            if let d = readDesk(u) { desk[d.cli] = d }
        }
    }

    private func notify(_ title: String, _ body: String) {
        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/usr/bin/osascript")
        p.arguments = ["-e", "display notification \"\(body)\" with title \"\(title)\" sound name \"Glass\""]
        try? p.run()
    }
}

func hm(_ t: TimeInterval) -> String {
    let m = Int(t) / 60
    return m >= 60 ? "\(m / 60)시간 \(m % 60)분" : "\(m)분"
}

struct UsageRow: View {
    let title: String
    let limit: Limit
    var body: some View {
        let pct = min(max(limit.pct, 0), 100)
        HStack(spacing: 8) {
            Text(title).font(.system(size: 11, weight: .medium)).foregroundStyle(.secondary)
                .frame(width: 30, alignment: .leading)
            GeometryReader { g in
                ZStack(alignment: .leading) {
                    Capsule().fill(.primary.opacity(0.08))
                    Capsule().fill(pct >= 80 ? Color.red : WorkState.working.color)
                        .frame(width: max(4, g.size.width * pct / 100))
                }
            }
            .frame(height: 6)
            Text("\(Int(pct.rounded()))%").font(.system(size: 11, weight: .semibold)).monospacedDigit()
                .frame(width: 34, alignment: .trailing)
            Text(resetText).font(.system(size: 10.5)).monospacedDigit().foregroundStyle(.tertiary)
                .frame(width: 104, alignment: .trailing)
        }
    }
    var resetText: String {
        guard let r = limit.resets else { return "초기화 시각 모름" }
        let left = r.timeIntervalSinceNow
        if left < 24 * 3600 { return "\(hm(left)) 뒤 초기화" }
        return r.formatted(.dateTime.weekday(.abbreviated).hour().minute()) + " 초기화"
    }
}

struct Stat: View {
    let value: String, caption: String
    var body: some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(value).font(.system(size: 17, weight: .semibold, design: .rounded)).monospacedDigit()
                .lineLimit(1).minimumScaleFactor(0.6)
            Text(caption).font(.system(size: 10.5)).foregroundStyle(.secondary)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding(.horizontal, 10).padding(.vertical, 8)
        .background(.quaternary.opacity(0.6), in: RoundedRectangle(cornerRadius: 8))
    }
}

struct Row: View {
    let e: Employee
    let open: () -> Void
    @State private var hover = false
    @State private var pulse = false
    var body: some View {
        Button(action: open) {
            HStack(alignment: .firstTextBaseline, spacing: 10) {
                dot.alignmentGuide(.firstTextBaseline) { $0[.bottom] - 1 }
                VStack(alignment: .leading, spacing: 3) {
                    HStack(alignment: .firstTextBaseline) {
                        Text(e.name).font(.system(size: 13, weight: e.unread ? .bold : .medium)).lineLimit(1)
                        Spacer(minLength: 8)
                        if hover && e.deskId != nil {
                            Image(systemName: "arrow.up.right").font(.system(size: 10, weight: .semibold))
                                .foregroundStyle(.secondary)
                        } else {
                            Text(e.label)
                                .font(.system(size: 10.5, weight: .semibold))
                                .foregroundStyle(e.state == .idle && !e.unread ? Color.secondary : e.color)
                            Text(e.state == .idle ? ago(e.last) : hm(Date().timeIntervalSince(e.since)))
                                .font(.system(size: 10.5)).monospacedDigit().foregroundStyle(.tertiary)
                        }
                    }
                    let sub = e.title.isEmpty ? e.task : [e.project, e.task].filter { !$0.isEmpty }.joined(separator: " · ")
                    if !sub.isEmpty {
                        Text(sub).font(.system(size: 11.5)).foregroundStyle(.secondary).lineLimit(1)
                    }
                }
            }
            .padding(.vertical, 7).padding(.horizontal, 8)
            .background(RoundedRectangle(cornerRadius: 7).fill(.primary.opacity(hover && e.deskId != nil ? 0.07 : 0)))
            .contentShape(Rectangle())
        }
        .buttonStyle(.plain)
        .onHover { hover = $0 }
    }

    // Busy sessions get a sonar ping so the panel feels alive.
    var dot: some View {
        let hollow = e.state == .idle && !e.unread
        return Circle()
            .strokeBorder(e.color, lineWidth: hollow ? 1.5 : 0)
            .background(Circle().fill(hollow ? .clear : e.color))
            .frame(width: 8, height: 8)
            .overlay {
                if e.state != .idle {
                    Circle().stroke(e.color, lineWidth: 1.5)
                        .scaleEffect(pulse ? 2.6 : 1).opacity(pulse ? 0 : 0.7)
                        .animation(.easeOut(duration: e.state == .waiting ? 0.9 : 1.6).repeatForever(autoreverses: false), value: pulse)
                        .onAppear { pulse = true }
                }
            }
    }

    func ago(_ d: Date) -> String {
        let m = Int(Date().timeIntervalSince(d)) / 60
        return m < 1 ? "방금" : "\(hm(Double(m * 60))) 전"
    }
}

/// This week's work time, Monday→Sunday.
struct Grass: View {
    let history: [Date: TimeInterval]
    var body: some View {
        let cal = Calendar.current
        let today = cal.startOfDay(for: Date())
        let monday = cal.date(byAdding: .day, value: -((cal.component(.weekday, from: today) + 5) % 7), to: today)!
        let days = (0..<7).map { cal.date(byAdding: .day, value: $0, to: monday)! }
        let total = days.reduce(0.0) { $0 + (history[$1] ?? 0) }
        VStack(alignment: .leading, spacing: 6) {
            HStack {
                Text("이번 주 잔디").font(.system(size: 11, weight: .medium)).foregroundStyle(.secondary)
                Spacer()
                Text("합계 \(hm(total))").font(.system(size: 11)).monospacedDigit().foregroundStyle(.tertiary)
            }
            HStack(spacing: 6) {
                ForEach(days, id: \.self) { day in
                    VStack(spacing: 4) {
                        RoundedRectangle(cornerRadius: 4)
                            .fill(day > today ? Color.primary.opacity(0.04) : fill(history[day] ?? 0))
                            .frame(height: 22)
                            .overlay(RoundedRectangle(cornerRadius: 4)
                                .strokeBorder(Color.primary.opacity(day == today ? 0.45 : 0), lineWidth: 1))
                            .help("\(day.formatted(.dateTime.month().day().weekday())) · \(hm(history[day] ?? 0))")
                        Text(day.formatted(.dateTime.weekday(.narrow)))
                            .font(.system(size: 10, weight: day == today ? .semibold : .regular))
                            .foregroundStyle(day == today ? .primary : .tertiary)
                    }
                    .frame(maxWidth: .infinity)
                }
            }
        }
    }
    func fill(_ t: TimeInterval) -> Color {
        let m = t / 60
        guard m >= 1 else { return .primary.opacity(0.08) }
        return WorkState.working.color.opacity(m < 30 ? 0.35 : m < 60 ? 0.55 : m < 120 ? 0.8 : 1)
    }
}

struct Panel: View {
    @ObservedObject var office: Office
    var body: some View {
        let r = office.report
        VStack(alignment: .leading, spacing: 12) {
            HStack(alignment: .firstTextBaseline) {
                Text("카피 출근부").font(.system(size: 14, weight: .semibold))
                Spacer()
                Text(Date().formatted(.dateTime.month().day().weekday()))
                    .font(.system(size: 11)).foregroundStyle(.secondary)
            }
            HStack(spacing: 6) {
                Stat(value: "\(r.staff.filter(\.needsYou).count)", caption: "확인 필요")
                Stat(value: "\(r.staff.filter { $0.state == .working }.count)", caption: "작업 중")
                Stat(value: hm(r.worked), caption: "오늘 근무")
            }
            if office.limits.five != nil || office.limits.week != nil {
                VStack(spacing: 7) {
                    if let l = office.limits.five { UsageRow(title: "5시간", limit: l) }
                    if let l = office.limits.week { UsageRow(title: "주간", limit: l) }
                }
                .padding(.vertical, 2)
            }
            if r.staff.isEmpty {
                Text("지금은 아무도 일하고 있지 않아요")
                    .font(.system(size: 12)).foregroundStyle(.secondary)
                    .frame(maxWidth: .infinity).padding(.vertical, 14)
            } else {
                VStack(spacing: 0) {
                    ForEach(Array(r.staff.enumerated()), id: \.element.id) { i, e in
                        if i > 0 { Divider().padding(.leading, 26).padding(.trailing, 8) }
                        Row(e: e) { office.open(e) }
                    }
                }
                .padding(.horizontal, -8)
            }
            Divider()
            Grass(history: office.history)
            Divider()
            HStack {
                if let c = r.clockIn {
                    Text("첫 출근 \(c.formatted(date: .omitted, time: .shortened))")
                        .font(.system(size: 11)).foregroundStyle(.tertiary)
                }
                Spacer()
                Text("⌃⌥⌘C 바로 이동").font(.system(size: 11)).foregroundStyle(.tertiary)
                Text("·").foregroundStyle(.quaternary)
                Button("종료") { NSApp.terminate(nil) }
                    .buttonStyle(.plain).font(.system(size: 11)).foregroundStyle(.secondary)
            }
        }
        .padding(14)
        .frame(width: 320)
    }
}

func selfTest() {
    let log = """
    {"ts":1000,"e":"SessionStart","sid":"a","cwd":"/x/nadeul"}
    {"ts":1010,"e":"UserPromptSubmit","sid":"a","cwd":"/x/nadeul","prompt":"fix login"}
    {"ts":1020,"e":"Notification","sid":"a","cwd":"/x/nadeul","msg":"Claude needs your permission to use Bash"}
    {"ts":1030,"e":"PostToolUse","sid":"a","cwd":"/x/nadeul"}
    {"ts":1070,"e":"Stop","sid":"a","cwd":"/x/nadeul"}
    {"ts":1080,"e":"Notification","sid":"a","cwd":"/x/nadeul","msg":"Claude is waiting for your input"}
    {"ts":1000,"e":"SessionStart","sid":"b","cwd":"/x/web"}
    {"ts":1100,"e":"UserPromptSubmit","sid":"b","cwd":"/x/web","prompt":"hi"}
    {"ts":1101,"e":"UserPromptSubmit","sid":"b","cwd":"/x/web","prompt":"<task-notification>done"}
    {"ts":1000,"e":"SessionStart","sid":"c","cwd":"/x/gone"}
    {"ts":1001,"e":"SessionEnd","sid":"c","cwd":"/x/gone"}
    """
    var r = parse(log, now: Date(timeIntervalSince1970: 1130))
    assert(r.orders == 3)
    assert(r.staff.first { $0.id == "b" }?.task == "hi", "system turns don't replace the task")
    assert(r.staff.count == 2, "ended session c removed")
    assert(r.staff.first { $0.id == "a" }?.state == .idle, "idle ping doesn't mean waiting")
    assert(r.staff.first { $0.id == "a" }?.done == Date(timeIntervalSince1970: 1070))
    assert(r.staff.first { $0.id == "b" }?.done == nil, "new order clears done")
    assert(r.ended.map(\.id) == ["c"], "clock-outs are reported")
    let fails = """
    {"ts":1,"e":"UserPromptSubmit","sid":"f","cwd":"/x/p","prompt":"go"}
    {"ts":2,"e":"PostToolUseFailure","sid":"f","cwd":"/x/p"}
    {"ts":3,"e":"PostToolUseFailure","sid":"f","cwd":"/x/p"}
    """
    assert(parse(fails, now: Date(timeIntervalSince1970: 4)).staff.first?.flailing == true)
    assert(parse(fails + "\n{\"ts\":4,\"e\":\"PostToolUse\",\"sid\":\"f\",\"cwd\":\"/x/p\"}", now: Date(timeIntervalSince1970: 5)).staff.first?.flailing == false, "a success resets")
    assert(r.staff.first { $0.id == "b" }?.state == .working)
    assert(r.worked == 60 + 30, "a: 1010→1070, b: 1100→now")
    r = parse(log.split(separator: "\n").prefix(3).joined(separator: "\n"), now: Date(timeIntervalSince1970: 1030))
    assert(r.staff.first?.state == .waiting)
    r = parse(log, now: Date(timeIntervalSince1970: 1130 + 4 * 3600))
    assert(r.staff.isEmpty, "stale sessions dropped")
    for p in [Pose.sleep] + (0..<4).flatMap({ [Pose.swim($0, night: true), .flail($0), .chew($0), .roll($0, urgent: true), .toss($0)] }) {
        let rows = poseRows(p)
        assert(rows.count == 15 && rows.allSatisfy { $0.count == 26 }, "\(p) must be 26×15")
    }
    print("selftest ok")
}

@main
struct CapyWorkApp: App {
    @StateObject private var office = Office()
    @StateObject private var ticker = Ticker()
    init() {
        if CommandLine.arguments.contains("--selftest") { selfTest(); exit(0) }
        NSApplication.shared.setActivationPolicy(.accessory)
    }
    var body: some Scene {
        MenuBarExtra {
            Panel(office: office)
        } label: {
            Image(nsImage: menuIcon(poses(), more: max(0, active().count - 5)))
        }
        .menuBarExtraStyle(.window)
    }

    // Busy or needs-you sessions each get a capybara; with none, one naps.
    private func active() -> [Employee] { office.report.staff.filter { $0.state != .idle || $0.unread } }

    private func poses() -> [Pose] {
        let hour = Calendar.current.component(.hour, from: Date())
        let night = hour >= 19 || hour < 5  // 야근: 7pm–5am
        let t = ticker.frame / 2  // 0.3s per frame; neglected approvals use the full 0.15s tick
        var poses: [Pose] = active().prefix(5).enumerated().map { i, e in
            switch e.state {
            case .working: return e.flailing ? .flail(t + i) : .swim(t + i, night: night)
            case .waiting:
                let urgent = Date().timeIntervalSince(e.since) > 300
                return .roll((urgent ? ticker.frame : t) + i, urgent: urgent)
            case .idle: return .chew(t + i)  // idle + unread
            }
        }
        poses += office.celebrating.map { .toss(Int(Date().timeIntervalSince($0) / 0.3)) }
        return poses.isEmpty ? [.sleep] : poses
    }
}
